name: Baixando Lista
on:
  schedule:
    - cron: '*/30 * * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        
    - name: execute py script 
      run: python agrupadordelistas.py   
      
    - name: Instalando streamlink
      run: |
         pip install --user --upgrade streamlink   
         
    - name: Instalando requests
      run: |
        pip install youtube-dl 
        pip install requests 
        pip install beautifulsoup4 
        pip install fastapi 
        pip install uvicorn 
        pip install schedule
        pip install selenium

      
  
       
    
       
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
