name: Update streams
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2

      - name: update streams
        run: py agrupadorlists.py

      - name: setup git config
        run: |
          git config user.name "M3UPT Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git commit -m "LISTAS AGRUPADAS"
          git push origin main
